// <auto-generated />
namespace ZenithWebSite.Migrations.SocietyMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tertiary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tertiary));
        
        string IMigrationMetadata.Id
        {
            get { return "201710150011413_Tertiary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
